### PR TITLE
Responsive Web Design (RWD) and media queries

### PR DESCRIPTION
**Pull request by alvp01**
This pull request will contain all the media queries and responsive design following the best practices dictated by the Microverse requirements

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @alvp01, I must say your project is awesome 😄 It is responsive and it has all the required features 👍 Congratulations 🎈 Before we can proceed and make the project even better, let us fix the comments below:
* The ```TNW``` logo is not appearing on the large screen size. Let us fix it as we have it on the original website. The following images will help us fix the problem
```Currently```
tnw
```Original```
tnw1
* Let us add a margin to the footer icons so it looks like the original
* Let us improve our README  file. We can take a look at this [template](https://github.com/microverseinc/readme-template) with screenshots

In our consequent projects, let our commit messages be in the ```present```. For example, ```fix``` instead ```fixed```, ```finish``` instead of ```finished```

Kindly make these changes and submit another review 👍 
Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by alvp01** [comment]
> ## Status: Require changes recycle traffic_light
> 
> Hi @alvp01, I must say your project is awesome smile It is responsive and it has all the required features +1 Congratulations balloon Before we can proceed and make the project even better, let us fix the comments below:
> 
>     * The `TNW` logo is not appearing on the large screen size. Let us fix it as we have it on the original website. The following images will help us fix the problem
>       `Currently`
>       tnw
>       `Original`
>       tnw1
> 
>     * Let us add a margin to the footer icons so it looks like the original
> 
>     * Let us improve our README  file. We can take a look at this [template](https://github.com/microverseinc/readme-template) with screenshots
> 
> 
> In our consequent projects, let our commit messages be in the `present`. For example, `fix` instead `fixed`, `finish` instead of `finished`
> 
> Kindly make these changes and submit another review +1
> Happy coding_ man_technologist
> [Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

Changes made. Thank your for your feed back.

**Review by serdg0 — APPROVED** [review]
**Status: Approved.**
### Great Job Abel! :100: :fireworks: 
Great job making the requested changes. Go on and merge to master :+1: 

Keep the great work in the next project! :muscle: 

### Happy Coding!!! :computer:

**Comment by alvp01** [comment]
> **Status: Approved.**
> ### Great Job Abel! 100 fireworks
> 
> Great job making the requested changes. Go on and merge to master +1
> 
> Keep the great work in the next project! muscle
> ### Happy Coding!!! computer

Thanks for your time. Happy weekend

**Pull request merged**
